version: '3.7'

services:
  backend:
    container_name: backend
    restart: unless-stopped
    image: kevin222004/ecommerce_backend:v1.0
    ports:
      - '8080:8080'
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    networks:
      - internal
    depends_on:
      - db

  frontend:
    container_name: frontend
    restart: unless-stopped
    image: kevin222004/ecommerce_frontend:v1.0
    environment:
      - NODE_PATH=/app/src
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - internal

  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: node-app
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - internal

networks:
  internal:

volumes:
  mongo_data: {}
  mongo_config: {}